version: "3.8"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    container_name: tgt_practice_frontend
    environment:
      - NODE_ENV=development