version: "3.8"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: tgt_practice_frontend
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://172.20.10.6:8000/graphql/
      - PORT=8000